# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52af05a67cf810fffb875bbcbddb23c68db5b4d207a9185415b231c78744a0c84d40e42e2d6d9a962d7d48079284c5c31c4713fdc795b71e85a4581e0b059880

test:
  secret_key_base: 12d29832ea201e8d3758e694d13fe5b88e06829a78e16ca882500d1be706e30d8c39e31d7ffcf2af596710803dc9ab88b162663a30ca5af84f29b959f44ba321

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
